app/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import models
from . import views

app_name = 'app'

urlpatterns = [
    url(r'^$', views.BinaListView.as_view(), name='bina-list'),
    url(r'^bina/ekle/$', views.ModelCreateView.as_view(model=models.Bina), name='bina-ekle'),
    url(r'^bina/guncelle/(?P<pk>[0-9]+)/$',
        views.ModelUpdateView.as_view(model=models.Bina),
        name='bina-guncelle'),
    url(r'^bina/sil/(?P<pk>[0-9]+)/$',
        views.BinaDeleteView.as_view(model=models.Bina),
        name='bina-sil'),

    url(r'^(?P<bina_slug>[-\w]+)/$', views.DaireListView.as_view(), name='daire-list'),
    url(r'^(?P<bina_slug>[-\w]+)/daire/ekle/$',
        views.ModelCreateView.as_view(model=models.Daire),
        name='daire-ekle'),
    url(r'^daire/guncelle/(?P<pk>[0-9]+)/$',
        views.ModelUpdateView.as_view(model=models.Daire),
        name='daire-guncelle'),
    url(r'^daire/sil/(?P<pk>[0-9]+)/$',
        views.DaireDeleteView.as_view(model=models.Daire),
        name='daire-sil'),

    url(r'^(?P<bina_slug>[-\w]+)/(?P<daire_pk>[0-9]+)/$',
        views.OdaListView.as_view(),
        name='oda-list'),
    url(r'^(?P<bina_slug>[-\w]+)/(?P<daire_pk>[0-9]+)/oda/ekle/$',
        views.ModelCreateView.as_view(model=models.Oda),
        name='oda-ekle'),
    url(r'^oda/guncelle/(?P<pk>[0-9]+)/$',
        views.ModelUpdateView.as_view(model=models.Oda),
        name='oda-guncelle'),
    url(r'^oda/sil/(?P<pk>[0-9]+)/$',
        views.OdaDeleteView.as_view(model=models.Oda),
        name='oda-sil'),

    url(r'^(?P<bina_slug>[-\w]+)/(?P<daire_pk>[0-9]+)/(?P<oda_slug>[-\w]+)/$',
        views.EsyaListView.as_view(),
        name='esya-list'),
    url(r'^(?P<bina_slug>[-\w]+)/(?P<daire_pk>[0-9]+)/(?P<oda_slug>[-\w]+)/esya/ekle/$',
        views.ModelCreateView.as_view(model=models.Esya),
        name='esya-ekle'),
    url(r'^esya/guncelle/(?P<pk>[0-9]+)/$',
        views.ModelUpdateView.as_view(model=models.Esya),
        name='esya-guncelle'),
    url(r'^esya/sil/(?P<pk>[0-9]+)/$',
        views.EsyaDeleteView.as_view(model=models.Esya),
        name='esya-sil'),
]

envantertakibi/envantertakibi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

ev-envanter-takibi/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_view

from app import views

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^ev-envanter-takibi/giris/', auth_view.login, name='login'),
    url(r'^ev-envanter-takibi/cikis/', auth_view.logout, name='logout'),
    url(r'^ev-envanter-takibi/kayit/', views.UserCreateView.as_view(), name='register')
]

app/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User


class Bina(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField('Bina Adi', max_length=100, unique=True)
    slug = models.SlugField(max_length=50)
    total_price = models.FloatField(default=0)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app:bina-list')

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug = slugify(self.name)
        super(Bina, self).save()


class Daire(models.Model):
    bina = models.ForeignKey(Bina, on_delete=models.CASCADE)
    no = models.IntegerField('Daire No')
    total_price = models.FloatField(default=0)

    def __unicode__(self):
        return "%s / Daire:%s" % (self.bina.name, self.no)

    def get_absolute_url(self):
        return reverse('app:daire-list', kwargs={'bina_slug': self.bina.slug})


class Oda(models.Model):
    daire = models.ForeignKey(Daire, on_delete=models.CASCADE)
    name = models.CharField('Oda Adi', max_length=100)
    slug = models.SlugField(max_length=50)
    total_price = models.FloatField(default=0)

    def __unicode__(self):
        return '%s / %s' % (self.daire, self.name)

    def get_absolute_url(self):
        return reverse('app:oda-list', kwargs={'bina_slug': self.daire.bina.slug,
                                               'daire_pk': self.daire.pk})

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug = slugify(self.name)
        super(Oda, self).save()


class Esya(models.Model):
    oda = models.ForeignKey(Oda, on_delete=models.CASCADE)
    name = models.CharField('Esya Adi', max_length=100)
    price = models.FloatField('Fiyat')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app:esya-list', kwargs={'bina_slug': self.oda.daire.bina.slug,
                                                'daire_pk': self.oda.daire.pk,
                                                'oda_slug': self.oda.slug})


def calculate_total_price(sender, instance, **kwargs):

    if instance.pk:
        old_obj = sender.objects.get(pk=instance.pk)
        old_price = old_obj.price
        new_price = instance.price - old_price
    else:
        new_price = instance.price

    instance.oda.total_price += new_price
    instance.oda.save()

    instance.oda.daire.total_price += new_price
    instance.oda.daire.save()

    instance.oda.daire.bina.total_price += new_price
    instance.oda.daire.bina.save()


pre_save.connect(calculate_total_price, sender=Esya)

app/templates/app/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Ev Envanter Takip Sistemi</h5>
      {% if user.is_authenticated %}
        <nav class="my-2 my-md-0 mr-md-3">
            <h4 class="p-2 text-dark">{{ user.username }}</h4>
        </nav>
        <a class="btn btn-outline-primary" href="{% url 'logout' %}">Cikis Yap</a>
      {% endif %}
    </div>
    <main role="main" class="container">
      <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <div class="panel panel-default panel-table">
          <div class="panel-heading" style="padding:10px">
            <div class="row align-items-center">
              <div class="col col-md-4">
                  {% block back_button %}{% endblock %}
              </div>
              <div class="col col-md-4">
                <h3 class="panel-title">{% block panel_title %}{% endblock %}</h3>
              </div>
              {% block panel_title_button %}{% endblock %}
            </div>
          </div>
          <div class="panel-body">
              {% block panel_body %}
                <table class="table table-striped table-bordered table-list">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        {% block table_column_title %}{% endblock %}
                        <th><em class="fa fa-cog"></em></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% block table_body %}{% endblock %}
                    </tbody>
                </table>
              {% endblock %}
          </div>
        </div>
      </div>
    </main>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

app/templates/app/bina_list.html
{% extends 'app/base.html' %}

{% block panel_title %}Ev Envanter Sistemi{% endblock %}

{% block panel_title_button %}
    <a type="button" href="{% url 'app:bina-ekle' %}" class="btn btn-sm btn-success">+ Yeni Bina</a>
{% endblock %}

{% block table_column_title %}
  <th scope="col">Binalar</th>
  <th scope="col">Daire Sayisi</th>
  <th scope="col">Toplam Degeri</th>
{% endblock %}

{% block table_body %}
  {% for bina in binalar %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ bina }}</td>
      <td>{{ bina.daire_set.all.count }}</td>
      <td>{{ bina.total_price }}</td>
      <td align="center">
        <a href="{% url 'app:daire-list' bina_slug=bina.slug %}" class="btn btn-outline-dark"><em class="fas fa-th"></em></a>
        <a href="{% url 'app:bina-guncelle' pk=bina.pk %}" class="btn btn-outline-dark"><em class="fas fa-redo"></em></a>
        <form action="{% url 'app:bina-sil' pk=bina.id %} " method="post">
          {% csrf_token %}
          <button class="btn btn-outline-danger" name="delete_item" value="{{ bina.id }}"><em class="fa fa-trash"></em></button>
        </form>
      </td>
    </tr>
  {% endfor %}
{% endblock %}

app/templates/app/daire_list.html
{% extends 'app/base.html' %}

{% block back_button %}
<a href="{% url 'app:bina-list' %}" class="btn btn-outline-secondary"><em class="far fa-arrow-alt-circle-left fa-2x"></em></a>
{% endblock %}

{% block panel_title %}{{ bina }}{% endblock %}

{% block panel_title_button %}
    <a type="button" href="{% url 'app:daire-ekle' bina_slug=bina.slug%}" class="btn btn-sm btn-success">+ Yeni Daire</a>
{% endblock %}

{% block table_column_title %}
  <th scope="col">Daireler</th>
  <th scope="col">Oda Sayisi</th>
  <th scope="col">Toplam Degeri</th>
{% endblock %}

{% block table_body %}
  {% for daire in daireler %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>Daire: {{ daire.no }}</td>
      <td>{{ daire.oda_set.all.count }}</td>
      <td>{{ daire.total_price }}</td>
      <td align="center">
        <a href="{% url 'app:oda-list' bina_slug=bina.slug  daire_pk=daire.pk %}" type="button" class="btn btn-outline-dark"><em class="fas fa-th"></em></a>
        <a href="{% url 'app:daire-guncelle' pk=daire.pk%}" class="btn btn-outline-dark"><em class="fas fa-redo"></em></a>
        <form action="{% url 'app:daire-sil' pk=daire.id %} " method="post">
          {% csrf_token %}
          <button class="btn btn-outline-danger" name="delete_item" value="{{ daire.id }}"><em class="fa fa-trash"></em></button>
        </form>
      </td>
    </tr>
  {% endfor %}
{% endblock %}

app/templates/app/esya_list.html
{% extends 'app/base.html' %}

{% block back_button %}
<a href="{% url 'app:oda-list' bina_slug=daire.bina.slug daire_pk=daire.pk %}" class="btn btn-outline-secondary"><em class="far fa-arrow-alt-circle-left fa-2x"></em></a>
{% endblock %}

{% block panel_title %}{{ daire }} / {{ oda }}{% endblock %}

{% block panel_title_button %}
    <a type="button" href="{% url 'app:esya-ekle' bina_slug=daire.bina.slug daire_pk=daire.pk oda_slug=oda.slug%}" class="btn btn-sm btn-success">+ Yeni Esya</a>
{% endblock %}

{% block table_column_title %}
  <th scope="col">Esyalar</th>
  <th scope="col">Deger</th>
{% endblock %}

{% block table_body %}
  {% for esya in esyalar %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ esya }}</td>
      <td>{{ esya.price }}</td>
      <td align="center">
        <a href="{% url 'app:esya-guncelle' pk=esya.pk%}" class="btn btn-outline-dark"><em class="fas fa-redo"></em></a>
        <form action="{% url 'app:esya-sil' pk=esya.id %} " method="post">
          {% csrf_token %}
          <button class="btn btn-outline-danger" name="delete_item" value="{{ esya.id }}"><em class="fa fa-trash"></em></button>
        </form>
      </td>
    </tr>
  {% endfor %}
{% endblock %}

app/templates/app/model_create_update_form.html
{% extends 'app/base.html' %}
{% block back_button %}{% endblock %}


{% block panel_title %}{{ panel_title }}{% endblock %}

{% block panel_body %}
    <div class="container">
      <form method="post">
        <div class="form-group">
            <div class="col-sm-5">
                <form method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success" value="Kaydet">Kaydet</button>
                </form>
                    <a href="{{ back_url }}" type="submit" class="btn btn-danger" name="iptal">Iptal</a>
            </div>
        </div>
      </form>
    </div>
{% endblock %}

app/templates/app/oda_list.html
{% extends 'app/base.html' %}

{% block back_button %}
<a href="{% url 'app:daire-list'  bina_slug=daire.bina.slug %}" class="btn btn-outline-secondary"><em class="far fa-arrow-alt-circle-left fa-2x"></em></a>
{% endblock %}

{% block panel_title %}{{ daire }}{% endblock %}

{% block panel_title_button %}
    <a type="button" href="{% url 'app:oda-ekle' bina_slug=daire.bina.slug daire_pk=daire.pk %}" class="btn btn-sm btn-success">+ Yeni Oda</a>
{% endblock %}

{% block table_column_title %}
  <th scope="col">Odalar</th>
  <th scope="col">Esya Sayisi</th>
  <th scope="col">Toplam Degeri</th>
{% endblock %}

{% block table_body %}
  {% for oda in odalar %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ oda }}</td>
      <td>{{ oda.esya_set.all.count }}</td>
      <td>{{ oda.total_price }}</td>
      <td align="center">
        <a href="{% url 'app:esya-list' bina_slug=daire.bina.slug  daire_pk=daire.pk oda_slug=oda.slug%}" class="btn btn-outline-dark"><em class="fas fa-th"></em></a>
        <a href="{% url 'app:oda-guncelle' pk=oda.pk%}" class="btn btn-outline-dark"><em class="fas fa-redo"></em></a>
        <form action="{% url 'app:oda-sil' pk=oda.id %} " method="post">
          {% csrf_token %}
          <button class="btn btn-outline-danger" name="delete_item" value="{{ oda.id }}"><em class="fa fa-trash"></em></button>
        </form>
      </td>
    </tr>
  {% endfor %}
{% endblock %}

app/templates/app/register.html
{% extends 'app/base.html' %}
{% block back_button %}{% endblock %}


{% block panel_title %}{{ panel_title }}{% endblock %}

{% block panel_body %}
    <div class="container">
      <form method="post">
        <div class="form-group">
            <div class="col-sm-5">
              <form method="post">
                {% csrf_token %}
                {% for field in form %}
                  <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  </p>
                {% endfor %}
                <button type="submit" class="btn btn-success">Kayit</button>
              </form>
                <a href="{% url 'login' %}" class="btn btn-danger" name="iptal">Iptal</a>
            </div>
        </div>
      </form>
    </div>
{% endblock %}